const mongoose = require('mongoose');

const todoItemSchema = new mongoose.Schema({
  student: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  course: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Course'
  },
  title: {
    type: String,
    required: [true, 'Todo title is required'],
    trim: true
  },
  description: {
    type: String,
    default: ''
  },
  type: {
    type: String,
    enum: ['assignment', 'quiz', 'discussion', 'reading', 'personal', 'other'],
    default: 'other'
  },
  linkedItem: {
    itemType: {
      type: String,
      enum: ['assignment', 'quiz', 'discussion', null],
      default: null
    },
    itemId: {
      type: mongoose.Schema.Types.ObjectId
    }
  },
  dueDate: {
    type: Date
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high'],
    default: 'medium'
  },
  isCompleted: {
    type: Boolean,
    default: false
  },
  completedAt: {
    type: Date
  },
  isAutoGenerated: {
    type: Boolean,
    default: false // true if created automatically from assignment/quiz
  }
}, {
  timestamps: true
});

// Indexes
todoItemSchema.index({ student: 1, isCompleted: 1 });
todoItemSchema.index({ student: 1, dueDate: 1 });
todoItemSchema.index({ course: 1, student: 1 });

module.exports = mongoose.model('TodoItem', todoItemSchema);
